export const PROGRESS_LIST = {
  request: 'TEACHING_PROGRESS_REQUEST',
  success: 'TEACHING_PROGRESS_SUCCESS',
  fail: 'TEACHING_PROGRESS_FAIL',
  update: 'TEACHING_PROGRESS_UPDATE',
};
export const CLEAR_PROGRESS_ERRORS = 'CLEAR_PROGRESS_ERRORS';
export const RESET_PROGRESS_STATE = 'RESET_PROGRESS_STATE';
